export { criarColunasProduto } from "./product-columns"
export { TabelaDadosProduto } from "./product-data-table"
export { ModalBuscaProduto } from "./product-search-modal"
export { TabelaProduto } from "./product-table"
export { produtosMock } from "../mock-data"
