import type { Product } from "./types"

// Mock data para produtos
export const mockProducts: Product[] = [
	{
		id: "1",
		codigo: "1847",
		descricao: "SUPER COMFORT 30% POLIAMIDA 10% ELASTANO",
		preco: 1.25,
		categoria: "Tecidos",
		unidade: "MT",
		peso: 0.125,
		empresa: 1,
		estoque: 150.5,
	},
	{
		id: "2",
		codigo: "1848",
		descricao: "SOFT TOUCH 50% ALGODÃO 50% POLIÉSTER",
		preco: 2.3,
		categoria: "Tecidos",
		unidade: "MT",
		peso: 0.18,
		empresa: 2,
		estoque: 89.75,
	},
	{
		id: "3",
		codigo: "4701",
		descricao: "POLIAMIDA PADRÃO 80% POLIAMIDA",
		preco: 1.85,
		categoria: "Tecidos",
		unidade: "MT",
		peso: 0.15,
		empresa: 1,
		estoque: 200.25,
	},
	{
		id: "4",
		codigo: "2156",
		descricao: "ALGODÃO PREMIUM 100% ALGODÃO",
		preco: 3.5,
		categoria: "Tecidos",
		unidade: "MT",
		peso: 0.22,
		empresa: 3,
		estoque: 75.8,
	},
	{
		id: "5",
		codigo: "3421",
		descricao: "ELASTANO FLEX 95% POLIÉSTER 5% ELASTANO",
		preco: 2.8,
		categoria: "Tecidos",
		unidade: "MT",
		peso: 0.165,
		empresa: 2,
		estoque: 120.4,
	},
	{
		id: "6",
		codigo: "1847",
		descricao: "SUPER COMFORT 30% POLIAMIDA 10% ELASTANO",
		preco: 1.25,
		categoria: "Tecidos",
		unidade: "MT",
		peso: 0.125,
		empresa: 1,
		estoque: 95.6,
	},
	{
		id: "7",
		codigo: "1848",
		descricao: "SOFT TOUCH 50% ALGODÃO 50% POLIÉSTER",
		preco: 2.3,
		categoria: "Tecidos",
		unidade: "MT",
		peso: 0.18,
		empresa: 3,
		estoque: 180.9,
	},
	{
		id: "8",
		codigo: "4701",
		descricao: "POLIAMIDA PADRÃO 80% POLIAMIDA",
		preco: 1.85,
		categoria: "Tecidos",
		unidade: "MT",
		peso: 0.15,
		empresa: 2,
		estoque: 65.3,
	},
	{
		id: "9",
		codigo: "2156",
		descricao: "ALGODÃO PREMIUM 100% ALGODÃO",
		preco: 3.5,
		categoria: "Tecidos",
		unidade: "MT",
		peso: 0.22,
		empresa: 1,
		estoque: 140.7,
	},
	{
		id: "10",
		codigo: "3421",
		descricao: "ELASTANO FLEX 95% POLIÉSTER 5% ELASTANO",
		preco: 2.8,
		categoria: "Tecidos",
		unidade: "MT",
		peso: 0.165,
		empresa: 3,
		estoque: 110.15,
	},
	{
		id: "11",
		codigo: "3421",
		descricao: "ELASTANO FLEX 95% POLIÉSTER 5% ELASTANO",
		preco: 2.8,
		categoria: "Tecidos",
		unidade: "MT",
		peso: 0.165,
		empresa: 2,
		estoque: 120.4,
	},
	{
		id: "12",
		codigo: "1847",
		descricao: "SUPER COMFORT 30% POLIAMIDA 10% ELASTANO",
		preco: 1.25,
		categoria: "Tecidos",
		unidade: "MT",
		peso: 0.125,
		empresa: 1,
		estoque: 95.6,
	},
	{
		id: "13",
		codigo: "1848",
		descricao: "SOFT TOUCH 50% ALGODÃO 50% POLIÉSTER",
		preco: 2.3,
		categoria: "Tecidos",
		unidade: "MT",
		peso: 0.18,
		empresa: 3,
		estoque: 180.9,
	},
	{
		id: "14",
		codigo: "4701",
		descricao: "POLIAMIDA PADRÃO 80% POLIAMIDA",
		preco: 1.85,
		categoria: "Tecidos",
		unidade: "MT",
		peso: 0.15,
		empresa: 2,
		estoque: 65.3,
	},
	{
		id: "15",
		codigo: "2156",
		descricao: "ALGODÃO PREMIUM 100% ALGODÃO",
		preco: 3.5,
		categoria: "Tecidos",
		unidade: "MT",
		peso: 0.22,
		empresa: 1,
		estoque: 140.7,
	},
	{
		id: "16",
		codigo: "3421",
		descricao: "ELASTANO FLEX 95% POLIÉSTER 5% ELASTANO",
		preco: 2.8,
		categoria: "Tecidos",
		unidade: "MT",
		peso: 0.165,
		empresa: 3,
		estoque: 110.15,
	},
]
